# Generated Python code from Sarana
# This file was automatically generated by the Sarana compiler

def add(a, b):
    return (a + b)

def multiply(a, b):
    result = 0
    counter = 0
    while (counter < b):
        result = (result + a)
        counter = (counter + 1)
    return result

sum = add(15, 25)
print("15 + 25 = ", sum)
product = multiply(6, 7)
print("6 * 7 = ", product)
def countdown(n):
    while (n > 0):
        print(n)
        n = (n - 1)
    print("Liftoff!")

print("Countdown from 5:")
countdown(5)
def fibonacci(n):
    a = 0
    b = 1
    count = 0
    while (count < n):
        print(a)
        temp = (a + b)
        a = b
        b = temp
        count = (count + 1)

print("Fibonacci sequence (first 8 numbers):")
fibonacci(8)
def max(a, b):
    if (a > b):
        return a
    else:
        return b

maximum = max(42, 17)
print("Max of 42 and 17: ", maximum)
def factorial(n):
    result = 1
    i = 1
    while (i <= n):
        result = (result * i)
        i = (i + 1)
    return result

fact5 = factorial(5)
print("5! = ", fact5)