# Generated Python code from Sarana
# This file was automatically generated by the Sarana compiler

A = 20
B = 40
C = (A + (B * B))
try:
    D = (C / 0)
except Exception:
    print("Error: Division by zero attempted but not allowed.")
print("The result is ", C)