"""
codegen.py
==========
Target Code Generator for Sarana

This module translates a Sarana Abstract Syntax Tree (AST) into executable
Python source code. This satisfies the "target code generation" requirement
of the compiler project (worth 8 marks).

The code generator walks the AST and emits Python code strings that can be
written to a .py file and executed with the standard Python interpreter.

Key Translation Rules:
    bloom x = 5;           →  x = 5
    echo "hello";          →  print("hello")
    when (x > 5) { }       →  if x > 5:
    otherwise { }          →  else:
    cycle (i < 3) { }      →  while i < 3:
    craft add(a, b) { }    →  def add(a, b):
    return x;              →  return x
    try { } ketch { }      →  try: ... except Exception: ...
    true / false           →  True / False
    and / or / not         →  and / or / not

The generated Python code is valid Python 3 and can be executed directly.
"""

from ast_nodes import *


class CodeGenerator:
    """
    Translates Sarana AST nodes into Python source code.
    
    Usage:
        generator = CodeGenerator()
        python_code = generator.generate(ast)
    """
    
    def __init__(self):
        self.indent_level = 0
        self.output = []
    
    def indent(self):
        """Increase indentation level."""
        self.indent_level += 1
    
    def dedent(self):
        """Decrease indentation level."""
        self.indent_level -= 1
    
    def emit(self, code):
        """
        Emit a line of Python code with current indentation.
        
        Args:
            code: Python code string to emit
        """
        indent_str = '    ' * self.indent_level
        self.output.append(indent_str + code)
    
    def generate(self, node):
        """
        Main entry point: generate Python code for an AST node.
        
        Args:
            node: AST node to translate
            
        Returns:
            str: Generated Python code
        """
        self.output = []
        self.indent_level = 0
        
        # Add header comment
        self.emit('# Generated Python code from Sarana')
        self.emit('# This file was automatically generated by the Sarana compiler')
        self.emit('')
        
        # Generate code for the AST
        self.visit(node)
        
        return '\n'.join(self.output)
    
    def visit(self, node):
        """
        Dispatch to appropriate visitor method based on node type.
        
        Args:
            node: AST node to visit
        """
        method_name = f'visit_{node.__class__.__name__}'
        visitor = getattr(self, method_name, self.generic_visit)
        return visitor(node)
    
    def generic_visit(self, node):
        """Fallback for nodes without specific visitor."""
        raise NotImplementedError(f'No visitor for {node.__class__.__name__}')
    
    # ═════════════════════════════════════════════════════════════════════
    # PROGRAM AND STATEMENTS
    # ═════════════════════════════════════════════════════════════════════
    
    def visit_Program(self, node):
        """Generate code for the entire program."""
        for statement in node.statements:
            self.visit(statement)
    
    def visit_BloomStatement(self, node):
        """
        Generate code for variable declaration.
        bloom x = 5;  →  x = 5
        """
        value_code = self.visit_expression(node.value)
        self.emit(f'{node.name} = {value_code}')
    
    def visit_EchoStatement(self, node):
        """
        Generate code for output statement.
        echo "hello" x;  →  print("hello", x)
        """
        expr_codes = [self.visit_expression(expr) for expr in node.expressions]
        self.emit(f'print({", ".join(expr_codes)})')
    
    def visit_WhenStatement(self, node):
        """
        Generate code for conditional.
        when (x > 5) { ... } otherwise { ... }
        →
        if x > 5:
            ...
        else:
            ...
        """
        condition_code = self.visit_expression(node.condition)
        self.emit(f'if {condition_code}:')
        
        self.indent()
        if node.then_body:
            for stmt in node.then_body:
                self.visit(stmt)
        else:
            self.emit('pass')
        self.dedent()
        
        if node.otherwise_body:
            self.emit('else:')
            self.indent()
            for stmt in node.otherwise_body:
                self.visit(stmt)
            self.dedent()
    
    def visit_CycleStatement(self, node):
        """
        Generate code for while loop.
        cycle (i < 10) { ... }
        →
        while i < 10:
            ...
        """
        condition_code = self.visit_expression(node.condition)
        self.emit(f'while {condition_code}:')
        
        self.indent()
        if node.body:
            for stmt in node.body:
                self.visit(stmt)
        else:
            self.emit('pass')
        self.dedent()
    
    def visit_CraftStatement(self, node):
        """
        Generate code for function definition.
        craft add(a, b) { return a + b; }
        →
        def add(a, b):
            return a + b
        """
        params = ', '.join(node.params)
        self.emit(f'def {node.name}({params}):')
        
        self.indent()
        if node.body:
            for stmt in node.body:
                self.visit(stmt)
        else:
            self.emit('pass')
        self.dedent()
        
        # Add blank line after function
        self.emit('')
    
    def visit_ReturnStatement(self, node):
        """
        Generate code for return statement.
        return x + 1;  →  return x + 1
        """
        if node.value:
            value_code = self.visit_expression(node.value)
            self.emit(f'return {value_code}')
        else:
            self.emit('return')
    
    def visit_TryKetchStatement(self, node):
        """
        Generate code for exception handling.
        try { ... } ketch { ... }
        →
        try:
            ...
        except Exception:
            ...
        """
        self.emit('try:')
        
        self.indent()
        if node.try_body:
            for stmt in node.try_body:
                self.visit(stmt)
        else:
            self.emit('pass')
        self.dedent()
        
        self.emit('except Exception:')
        
        self.indent()
        if node.ketch_body:
            for stmt in node.ketch_body:
                self.visit(stmt)
        else:
            self.emit('pass')
        self.dedent()
    
    def visit_ExpressionStatement(self, node):
        """
        Generate code for expression statement (e.g., function call).
        add(1, 2);  →  add(1, 2)
        """
        expr_code = self.visit_expression(node.expression)
        self.emit(expr_code)
    
    # ═════════════════════════════════════════════════════════════════════
    # EXPRESSIONS
    # ═════════════════════════════════════════════════════════════════════
    
    def visit_expression(self, node):
        """
        Visit an expression node and return the generated code string.
        Unlike statement visitors which emit code, expression visitors
        return code strings that can be composed.
        """
        method_name = f'visit_expr_{node.__class__.__name__}'
        visitor = getattr(self, method_name, None)
        
        if visitor:
            return visitor(node)
        else:
            raise NotImplementedError(f'No expression visitor for {node.__class__.__name__}')
    
    def visit_expr_BinaryOp(self, node):
        """
        Generate code for binary operation.
        a + b  →  a + b
        """
        left_code = self.visit_expression(node.left)
        right_code = self.visit_expression(node.right)
        
        # Handle operator translation
        operator = node.operator
        
        # Wrap in parentheses to preserve precedence
        return f'({left_code} {operator} {right_code})'
    
    def visit_expr_UnaryOp(self, node):
        """
        Generate code for unary operation.
        -x  →  -x
        not x  →  not x
        """
        operand_code = self.visit_expression(node.operand)
        operator = node.operator
        
        if operator in ['not']:
            return f'{operator} {operand_code}'
        else:
            return f'{operator}{operand_code}'
    
    def visit_expr_Variable(self, node):
        """
        Generate code for variable reference.
        x  →  x
        """
        return node.name
    
    def visit_expr_Integer(self, node):
        """
        Generate code for integer literal.
        42  →  42
        """
        return str(node.value)
    
    def visit_expr_Float(self, node):
        """
        Generate code for float literal.
        3.14  →  3.14
        """
        return str(node.value)
    
    def visit_expr_String(self, node):
        """
        Generate code for string literal.
        "hello"  →  "hello"
        """
        # Escape quotes in the string
        escaped = node.value.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{escaped}"'
    
    def visit_expr_Boolean(self, node):
        """
        Generate code for boolean literal.
        true  →  True
        false  →  False
        """
        return 'True' if node.value else 'False'
    
    def visit_expr_Array(self, node):
        """
        Generate code for array literal.
        [1, 2, 3]  →  [1, 2, 3]
        """
        element_codes = [self.visit_expression(elem) for elem in node.elements]
        return f'[{", ".join(element_codes)}]'
    
    def visit_expr_FunctionCall(self, node):
        """
        Generate code for function call.
        add(1, 2)  →  add(1, 2)
        """
        arg_codes = [self.visit_expression(arg) for arg in node.arguments]
        return f'{node.name}({", ".join(arg_codes)})'
    
    def visit_expr_Assignment(self, node):
        """
        Generate code for assignment (used in some expression contexts).
        x = 5  →  x = 5
        
        Note: This is for assignments within expressions, not bloom statements.
        """
        value_code = self.visit_expression(node.value)
        return f'{node.name} = {value_code}'


# ═════════════════════════════════════════════════════════════════════════
# PUBLIC API
# ═════════════════════════════════════════════════════════════════════════

def generate(ast):
    """
    Generate Python code from a Sarana AST.
    
    Args:
        ast: Program node (root of AST)
        
    Returns:
        str: Generated Python source code
        
    Example:
        >>> from lexer import tokenize
        >>> from parser import parse
        >>> from codegen import generate
        >>> 
        >>> code = 'bloom x = 5; echo x;'
        >>> tokens = tokenize(code)
        >>> ast = parse(tokens)
        >>> python_code = generate(ast)
        >>> print(python_code)
        # Generated Python code from Sarana
        # This file was automatically generated by the Sarana compiler
        
        x = 5
        print(x)
    """
    generator = CodeGenerator()
    return generator.generate(ast)


def generate_to_file(ast, output_path):
    """
    Generate Python code and write it to a file.
    
    Args:
        ast: Program node (root of AST)
        output_path: Path to output .py file
        
    Returns:
        str: Generated Python source code (also written to file)
        
    Example:
        >>> from codegen import generate_to_file
        >>> generate_to_file(ast, 'output/generated.py')
    """
    python_code = generate(ast)
    
    with open(output_path, 'w') as f:
        f.write(python_code)
    
    return python_code
